
#数据库配置
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/book?serverTimezone=GMT%2B8&useSSL=true
      username: root
      password: mysql
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

        # 这里我使用了devtool热部署技术，这样就不需要每次都重启服务！！-->
    debug: true
    spring:
        devtools:
            restart:
                enabled: true  #设置开启热部署
        freemarker:
            cache: false    #页面不加载缓存，修改即时生效
